# Generated by Django 3.2 on 2024-07-28 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g4l', '0005_auto_20240727_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='todo',
            new_name='titles',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='description',
        ),
        migrations.AddField(
            model_name='schedule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
