# Generated by Django 3.2 on 2024-07-29 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g4l', '0006_auto_20240728_0314'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to='g4l.schedule'),
        ),
    ]
