# Generated by Django 3.2 on 2024-07-29 04:11

from django.db import migrations

def set_default_schedule(apps, schema_editor):
    TodoList = apps.get_model('g4l', 'TodoList')
    Schedule = apps.get_model('g4l', 'Schedule')
    default_schedule = Schedule.objects.first()  # or create a default schedule if necessary
    for todo in TodoList.objects.all():
        todo.schedule = default_schedule
        todo.save()

class Migration(migrations.Migration):

    dependencies = [
        ('g4l', '0007_todolist_schedule'),
    ]

    operations = [
        migrations.RunPython(set_default_schedule),
    ]

