# Generated by Django 3.2 on 2024-07-29 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('g4l', '0008_auto_20240729_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todolist', to='g4l.schedule'),
        ),
    ]
