# Generated by Django 3.2 on 2024-07-29 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g4l', '0009_alter_todolist_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='job_type',
            field=models.CharField(choices=[('daily', 'Công việc hàng ngày'), ('weekly', 'Ngày trong tuần'), ('monthly', 'Ngày trong tháng'), ('one_time', 'Làm trong ngày')], default='one_time', max_length=10),
        ),
    ]
