# Generated by Django 3.2 on 2024-07-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g4l', '0011_alter_todolist_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todolist',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='job_type',
            field=models.CharField(choices=[('Daily', 'Hàng ngày'), ('Weekly', 'Ngày trong tuần'), ('Monthly', 'Ngày trong tháng'), ('One_time', 'Làm trong ngày')], default='one_time', max_length=10),
        ),
    ]
