# Generated by Django 3.2 on 2024-08-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('g4l', '0013_auto_20240805_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='day_of_month',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='todolist',
            name='days_of_month',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='todolist',
            name='days_of_week',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
