# Generated by Django 3.2 on 2024-08-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('g4l', '0015_auto_20240808_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='completed',
        ),
    ]
